es_host:
  - localhost

tika_host:
  - localhost

#auth:
#  user: gransk
#  pass: gransk

name_model: 'utils/names.gz'

subscribers:
  - gransk.core.process
  - gransk.core.magic
  - gransk.plugins.extractors.file_meta
  - gransk.plugins.extractors.picture_meta
  - gransk.plugins.extractors.tika_extractor
  - gransk.plugins.extractors.strings
  - gransk.plugins.extractors.ewf_strings
  - gransk.plugins.unpackers.unpack_diskimage
  - gransk.plugins.unpackers.unpack_archive
  - gransk.plugins.find.find_entities
  - gransk.plugins.find.polyglot_ner
  - gransk.plugins.find.find_names_brute
  - gransk.plugins.storage.copy_file
  - gransk.plugins.storage.copy_picture
  - gransk.plugins.storage.es_index
  - gransk.plugins.analysis.related_documents
  - gransk.plugins.analysis.related_entities
  - gransk.plugins.analysis.entity_network
  #- gransk.plugins.storage.store_text

copy_ext:
  - pdf
  - doc
  - docx
  - xls
  - xlsx
  - ppt
  - pptx

entities:
  user_id:
    pattern: "[0-9\\w\\-][0-9\\w\\-\\.+]+@[0-9\\w\\-][0-9\\w\\-\\.]+\\.[a-z]{1,4}"
    test:
      - "post@pcbje.com"
      - "other@example.com"

  ip_addr:
    pattern: "[0-9]{1,3}(?:[\\.][0-9]{1,3}){3}"
    test: "192.168.0.1"

  #timestamp:
  #  pattern: "201[0-9]-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2}"
  #  test: "2013-10-30 14:35:31"

  bitcoin_addr:
    pattern: "1[a-km-zA-HJ-NP-Z0-9]{25,34}"
    test: "15ckupwoyBaikj5SCKeUNzKAF92unvGpNk"

  url:
    pattern: "http[s]?://(?:[a-zA-Z]|[0-9]|[$-_@.&+]|[!*\\(\\),]|(?:%[0-9a-fA-F][0-9a-fA-F]))+"
    test: "http://pcbje.com"

blacklist:
  - thumbs.db
  - .ds_store

ext_types:
  diskimage:
    - e01
    - bin
    - dd
    - raw
    - '001'

  archive:
    - rar
    - zip
    - 7z
    - tgz
    - gz
    - tar

  picture:
    - png
    - jpg
    - jpeg
    - bmp
    - png
    - tiff
    - tif

  document:
    - pdf
    - docx
    - doc
    - xlsx
    - xls
    - pptx
    - ppt

  ignored:
    - aac
    - css
    - dll
    - gif
    - js
    - wpl
    - dat
    - bmp
    - class
    - plist
    - thumb
